#!/bin/bash

tag=$(cat package.json | jq -r ".version")
name=$(cat package.json | jq -r ".scala-docker")
repository="$AWS_ACCOUNT.dkr.ecr.region.amazonaws.com/$name"

# docker build
docker build -t $repository:$tag .

