#!/bin/bash

tag=$(cat package.json | jq -r ".version")
name=$(cat package.json | jq -r ".name")
repository="$AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$name"

# docker build
docker build -t $repository:$tag .

