#!/bin/bash

tag=$(cat package.json | jq -r ".version")
name=$(cat package.json | jq -r ".scala-docker")
repository="$AWS_ACCOUNT.dkr.ecr.region.amazonaws.com/$name"

if [[ -z $ENV_ROLE_ARN ]]; then
  echo "Using CodeBuild configured role for deployment"
  # configure ecr
  $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)

  docker push $repository:$tag

else
  echo "Assuming role $ENV_ROLE_ARN for deployment"
  aws sts assume-role --role-arn $ENV_ROLE_ARN --role-session-name $(uuidgen) --query "Credentials" > tmp
  awsAccessKeyId=$(cat tmp | jq -r ".AccessKeyId")
  awsSecretAccessKey=$(cat tmp | jq -r ".SecretAccessKey" )
  awsSessionToken=$(cat tmp | jq -r ".SessionToken" )
  # let's keep these in script variables so that we can immediately remove the tmp file with secrets
  rm -f tmp

fi
