AWSTemplateFormatVersion: '2010-09-09'
Description: Docker image repository for docker-scala

Parameters:
  RepositoryName:
    Type: String

Resources:

  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName

Outputs: {}
